image:
  repository: registry.cn-shanghai.aliyuncs.com/your-org/growforever-main
  tag: latest

service:
  port: 3000

ingress:
  enabled: true
  host: www.growforever.com
  tls:
    enabled: true
    secretName: growforever-tls
