services:
  postgres:
    image: postgres:latest
    container_name: growforever-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: iammm
      POSTGRES_DB: growforever
    ports:
      - "5432:5432"
    volumes:
      - growforever_postgres_data:/var/lib/postgresql/data
    networks:
      - growforever-api

  neo4j:
    image: neo4j:latest
    container_name: growforever-neo4j
    ports:
      - "7474:7474"   # HTTP 界面
      - "7687:7687"   # Bolt 协议
    volumes:
      - growforever_neo4j_data:/data
    networks:
      - growforever-api

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "16333:6333" # Qdrant HTTP & gRPC 默认端口
    volumes:
      - growforever-qdrant_data:/qdrant/storage
    networks:
      - growforever-api

networks:
  growforever-api:
    driver: bridge

volumes:
  growforever_postgres_data:
  growforever_neo4j_data:
  growforever-qdrant_data:
