services:
  postgres:
    image: postgres:latest
    container_name: growforever-postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - growforever-api

  neo4j:
    image: neo4j:latest
    container_name: growforever-neo4j
    environment:
      # Docker 官方要求的认证格式：用户名/密码
      NEO4J_AUTH: "${NEO4J_USER}/${NEO4J_PASSWORD}"
      # 如果想关 strict 验证也可以加这行：
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
    networks:
      - growforever-api

  qdrant:
    image: qdrant/qdrant:latest
    container_name: growforever-qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - growforever-api

networks:
  growforever-api:
    driver: bridge

volumes:
  pg_data:
  neo4j_data:
  qdrant_data:
