services:
  postgres:
    image: postgres:latest
    container_name: growforever-postgres
    env_file:
      - .env
    environment:
      # postgres 官方镜像会读取这三个变量来初始化数据库
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: iammm
      POSTGRES_DB: growforever
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - growforever_postgres_data:/var/lib/postgresql/data
    networks:
      - growforever-api

  neo4j:
    image: neo4j:latest
    container_name: growforever-neo4j
    ports:
      - "7474:7474"   # HTTP 界面
      - "7687:7687"   # Bolt 协议
    volumes:
      - growforever_neo4j_data:/data
    networks:
      - growforever-api

networks:
  growforever-api:
    driver: bridge

volumes:
  growforever_postgres_data:
  growforever_neo4j_data:
