apiVersion: apps/v1
kind: Deployment
metadata:
  name: growforever-main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: growforever-main
  template:
    metadata:
      labels:
        app: growforever-main
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
