name: growforever
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - psycopg2
  - pytorch=2.1.0
  - pytorch-cuda=11.8
  - torchvision=0.16.0
  - torchaudio=2.1.0
  - pyarrow                       # ← 加在这里，conda 安装它
  - pip
  - pip:
    - fastapi>=0.115.12,<0.116.0
    - uvicorn>=0.34.0,<0.35.0
    - sqlalchemy>=2.0
    - psycopg2-binary>=2.9
    - neo4j>=5.15
    - python-dotenv>=1.0.1
    - pydantic>=2.6
    - pydantic-settings>=2.2.1
    - scikit-learn>=1.4
    - numpy>=1.26,<2.0
    - pandas>=2.2
    - torch-geometric>=2.4.0
    - transformers>=4.39
    - datasets>=2.18
    - scipy
    - tqdm
    - passlib[bcrypt]
    - pydantic[email]
    - pyjwt
    - qdrant_client
    - openai
    - python-jose[cryptography]
    - python-multipart