name: CI/CD for growforever-main (frontend)

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/**'
      - 'helm/growforever-main/**'

env:
  IMAGE_NAME: registry.cn-shanghai.aliyuncs.com/your-org/growforever-main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to ACR
        uses: docker/login-action@v2
        with:
          registry: registry.cn-shanghai.aliyuncs.com
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -f frontend/Dockerfile -t $IMAGE_NAME:${{ github.sha }} .
          docker push $IMAGE_NAME:${{ github.sha }}

      - name: Setup kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml
          export KUBECONFIG=$PWD/kubeconfig.yaml

      - name: Deploy with Helm
        run: |
          helm upgrade --install growforever-main ./helm/growforever-main \
            --set image.repository=$IMAGE_NAME \
            --set image.tag=${{ github.sha }}
